import { Document, Paragraph, TextRun, HeadingLevel, Packer, AlignmentType, BorderStyle } from "docx";

// ─── DOCX Builder ────────────────────────────────────────────────────────────

const HEADING_PATTERN = /^[A-Z][A-Z\s&/\-]{2,}$/;
const BULLET_PATTERN = /^[•\-\*]\s/;
const JOB_LINE_PATTERN = /^(.+?)\s*[\|\/\\]\s*(.+?)\s*[\|\/\\]\s*(.+)$/;

export async function buildDocxBuffer(
  cvText: string,
  jobTitle: string,
  company: string,
): Promise<Buffer> {
  const rawLines = cvText.split("\n");
  const children: Paragraph[] = [];

  let i = 0;
  while (i < rawLines.length) {
    const line = rawLines[i];
    const trimmed = line.trim();

    // Blank line → explicit spacing paragraph
    if (trimmed.length === 0) {
      children.push(new Paragraph({ spacing: { after: 100 } }));
      i++;
      continue;
    }

    // All-caps short line → section heading
    if (HEADING_PATTERN.test(trimmed) && trimmed.length < 60) {
      children.push(
        new Paragraph({
          children: [
            new TextRun({
              text: trimmed,
              bold: true,
              size: 26,
              allCaps: true,
            }),
          ],
          spacing: { before: 280, after: 80 },
          border: {
            bottom: {
              color: "AAAAAA",
              size: 6,
              style: BorderStyle.SINGLE,
              space: 4,
            },
          },
        }),
      );
      i++;
      continue;
    }

    // Bullet point
    if (BULLET_PATTERN.test(trimmed)) {
      children.push(
        new Paragraph({
          children: [
            new TextRun({
              text: trimmed.replace(/^[•\-\*]\s*/, ""),
              size: 22,
            }),
          ],
          bullet: { level: 0 },
          spacing: { after: 60 },
        }),
      );
      i++;
      continue;
    }

    // Job/role line: "Company | Title | Date" or "Company | Title"
    if (JOB_LINE_PATTERN.test(trimmed)) {
      const parts = trimmed.split(/\s*[\|\/\\]\s*/);
      children.push(
        new Paragraph({
          children: parts.flatMap((part, idx) => [
            new TextRun({
              text: part.trim(),
              bold: idx === 0,
              size: 22,
            }),
            ...(idx < parts.length - 1
              ? [new TextRun({ text: "  ·  ", size: 22, color: "888888" })]
              : []),
          ]),
          spacing: { before: 120, after: 60 },
        }),
      );
      i++;
      continue;
    }

    // First line of document often the candidate name (short, title-case)
    if (i === 0 && trimmed.length < 60 && /^[A-Z][a-z]/.test(trimmed)) {
      children.push(
        new Paragraph({
          children: [
            new TextRun({
              text: trimmed,
              bold: true,
              size: 36,
            }),
          ],
          alignment: AlignmentType.CENTER,
          spacing: { after: 60 },
        }),
      );
      i++;
      continue;
    }

    // Default paragraph
    children.push(
      new Paragraph({
        children: [new TextRun({ text: trimmed, size: 22 })],
        spacing: { after: 80 },
      }),
    );
    i++;
  }

  const doc = new Document({
    creator: "ParsePilot AI",
    title: `${jobTitle} — ${company} CV`,
    description: "ATS-optimized CV generated by ParsePilot AI",
    styles: {
      default: {
        document: {
          run: {
            font: "Calibri",
            size: 22,
          },
        },
      },
    },
    sections: [
      {
        properties: {
          page: {
            margin: {
              top: 720,
              right: 720,
              bottom: 720,
              left: 720,
            },
          },
        },
        children,
      },
    ],
  });

  const buffer = await Packer.toBuffer(doc);
  return Buffer.from(buffer);
}

// ─── Print-optimized HTML Builder ────────────────────────────────────────────

export function buildPrintHtml(
  text: string,
  title: string,
  company: string,
  docType: "cv" | "cover",
): string {
  const escapedText = text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");

  const pageTitle = docType === "cover"
    ? `Cover Letter — ${company}`
    : `CV — ${title} at ${company}`;

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${pageTitle}</title>
  <style>
    /* Screen styles */
    * { box-sizing: border-box; margin: 0; padding: 0; }

    body {
      font-family: 'Calibri', 'Arial', sans-serif;
      font-size: 11pt;
      line-height: 1.55;
      color: #1a1a1a;
      background: #f5f5f5;
    }

    .print-banner {
      background: #1a1a2e;
      color: #fff;
      padding: 14px 24px;
      display: flex;
      align-items: center;
      justify-content: space-between;
      gap: 12px;
      flex-wrap: wrap;
    }

    .print-banner p { font-size: 13px; opacity: 0.85; margin-top: 2px; }

    .print-btn {
      background: #6d28d9;
      color: #fff;
      border: none;
      padding: 8px 20px;
      border-radius: 6px;
      font-size: 14px;
      font-weight: 600;
      cursor: pointer;
      white-space: nowrap;
    }

    .print-btn:hover { background: #7c3aed; }

    .document {
      max-width: 850px;
      margin: 24px auto;
      background: #fff;
      padding: 56px 64px;
      border-radius: 4px;
      box-shadow: 0 2px 20px rgba(0,0,0,0.10);
    }

    pre {
      white-space: pre-wrap;
      word-wrap: break-word;
      font-family: 'Calibri', 'Arial', sans-serif;
      font-size: 11pt;
      line-height: 1.55;
      color: #1a1a1a;
    }

    /* Print styles */
    @media print {
      body { background: white; font-size: 11pt; }
      .print-banner { display: none !important; }
      .document {
        margin: 0;
        padding: 0.4in;
        box-shadow: none;
        border-radius: 0;
        max-width: 100%;
      }
      pre { font-size: 11pt; }
    }

    @page {
      size: A4;
      margin: 0.5in;
    }
  </style>
</head>
<body>
  <div class="print-banner">
    <div>
      <strong>ParsePilot AI — ${pageTitle}</strong>
      <p>Use Ctrl+P (or Cmd+P on Mac) → Save as PDF for best results. Uncheck "Headers and footers" in print options.</p>
    </div>
    <button class="print-btn" onclick="window.print()">⬇ Print / Save as PDF</button>
  </div>

  <div class="document">
    <pre>${escapedText}</pre>
  </div>

  <script>
    // Auto-open print dialog after a brief render delay
    if (!window.location.search.includes('noprint')) {
      window.addEventListener('load', function() {
        setTimeout(function() { window.print(); }, 600);
      });
    }
  </script>
</body>
</html>`;
}
